--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Olybear9/Mavoric
build-by-default: true
branches:
- stable
- master
projects:
  Mavoric:
    path: ""
    logo: "resources/assets/mavoric_black_and_white.png"
...
