# Config version, recommended to not touch this, will cause config to be overwrote
Version: 2.0.0-alpha
Webhooks:
  alerts: false
  system: false
  reports: false
Options:
  developer-mode: true # Whether or not to forcefully enable developer features
  packet-detection: false # Determine whether a packet is geninue
  