Version: 0.1.7 # DO NOT CHANGE THIS!
Webhooks:
  alert-deny: false # Discord URL to enable
  alert-grant: false # Discord URL to enable
  alerts: false # Discord URL to enable
  reports: false # Discord URL to enable
Autoban:
  violation-count: 20 # Autoban after x violations of a specific cheat
  max-violation: 30 # Autoban if x or more violations
  disabled: false # set this to true for no auto bans.
  vague-reasoning: true # set this to false if you want mavoric to put "PLAYER WAS BANNED FOR {CHEAT}" instead of "PLAYER WAS BANNED FOR CHEATING"
Alerts:
  tps: 17 # At 15 tps warn online staff members.
  tps-low: 10 # Below 10 tps warn online staff members.
Reports: true
Suppression: true # This applies to all cheats, should mavoric cancel events if cheating
AllowNPC: true # Self explainitory
ShareData: true # This is recommended to help improve future mavoric versions.
Debugging: false # Debug messages. (really spammy.)

# These are settings for each cheat, some of these are not configured
Cheats:
  Flight:
    enabled: false
    suppression: true
    autoban: false
  Reach:
    enabled: true
    suppression: true
    detect-lag: true
    use-mav-netwrk: true
  MultiAura:
    enabled: true
    suppression: true
    use-mav-netwrk: false
  KillAura:
    enabled: false
    suppression: true
  Speed:
    enabled: true
    suppression: true
  AutoClicker:
    enabled: true
    suppression: true
    max-cps: 24
  AimBot:
    enabled: true
    suppression: true
  FastEat:
    enabled: true
    suppression: true
  Phase:
    enabled: true
    suppression: true
  NoClip:
    enabled: true
    suppression: true
  Teleport:
    enabled: true
    suppression: true
  HighJump:
    enabled: true
    suppression: true
  FastBreak:
    enabled: true
    suppression: true
  
  