Version: 1.0.2 # DO NOT CHANGE THIS!
Webhooks:
  # All of the following accept a DISCORDWEBHOOKURL or false.
  alert-deny: false
  alert-grant: false
  alerts: false
  reports: false

Autoban:
  # Should autobans be enabled? (IF THIS IS ENABLED, BANWAVES ARE OVERRIDDEN REGARDLESS IF BANWAVES ARE ENABLED!)
  enabled: yes
  # If enabled, you can select type "KICK" or "BAN"
  type: kick
  # After how many violations should a player be banned/kicked? (50-80 is recommended)
  max-violations: 60
  # What should the reason be for a ban? (Note, actual reasons are stored in a database.)
  ban-reason: ยง4Illegal client modifications.
  # Increment ban times? (If a player has been banned/kicked, go to level 2) This is not implemeneted yet.
  timebans:
    ban-1: 10d
    ban-2: 30d
    ban-3: 60d
    ban-4: never

Banwaves: 
  # Are banwaves enabled on this server?
  enabled: no
  # Should banwaves be automatically issued after a certain amount of players are on it? If so, put the number here.
  auto-issue: no 
  # After how many violations should a player be added to a wave?
  violations: 53
  # After how many violations should a player be banned if they're in a wave. Put "no" for never.
  max-violations: 200

Alerts:
  # Should mavoric alert staff with the "mavoric.alerts" permission / OP players
  enabled: yes
  # Should staff be allowed to decline and accept alerts?
  command: yes
  # If banwaves are enabled, should a denial of a alert remove them from the wave?
  remove-wave: yes

Suppression:
  # Should mavoric suppression be enabled?
  enabled: yes
  # Should all cheats be suppressed?
  all-cheats: yes
  # If the master override is off, provide the cheats that should be suppressed.
  cheats:
    - KillAura
    - Speed
    - AutoClicker
    - Reach

Cheats:
  # list of disabled cheats.
  disabled: []
  

